"""Generate the NeuroML network + LEMS simulation that runs a protocol battery.

Every protocol becomes its own single-cell population receiving its own inputs, so a
whole battery for one variant runs in a single jLEMS process (cells are uncoupled).
Probe files are written next to the model's cell file so the model's own relative
includes resolve exactly as they do in the shipped harness.
"""

from __future__ import annotations

import dataclasses as dc
import re
from collections import defaultdict
from collections.abc import Sequence
from pathlib import Path
from xml.sax.saxutils import quoteattr

from neuraxis.models import Workspace
from neuraxis.schemas import ConcreteProtocol, ExecConfig, ModelRecord, StimulusComponent
from neuraxis.simulators.base import OutputSpec
from neuraxis.units import format_number

_NMLID = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
PROBE_NET_ID = "ns_net"
PROBE_SIM_ID = "ns_sim"
DEFAULT_SEED = 12345


@dc.dataclass(frozen=True)
class ProbeBundle:
    lems_file: Path
    net_file: Path
    output: OutputSpec
    length_ms: float
    protocol_ids: tuple[str, ...]
    cell_steps: int          # cells x steps, the simulator-independent cost measure


def population_id(protocol_id: str) -> str:
    pid = f"ns_{protocol_id}"
    if not _NMLID.match(pid):
        raise ValueError(f"protocol id {protocol_id!r} is not a valid NeuroML id")
    return pid


def _component_xml(cid: str, c: StimulusComponent) -> str:
    if c.kind == "pulse":
        return (f'    <pulseGenerator id="{cid}" delay="{format_number(c.delay_ms)}ms" '
                f'duration="{format_number(c.duration_ms)}ms" amplitude="{format_number(c.amplitude_nA)}nA"/>')
    if c.kind == "ramp":
        return (f'    <rampGenerator id="{cid}" delay="{format_number(c.delay_ms)}ms" '
                f'duration="{format_number(c.duration_ms)}ms" startAmplitude="{format_number(c.start_nA)}nA" '
                f'finishAmplitude="{format_number(c.finish_nA)}nA" baselineAmplitude="{format_number(c.baseline_nA)}nA"/>')
    raise ValueError(f"unsupported stimulus component kind {c.kind!r}")


def network_xml(model: ModelRecord, cell_include: str, protocols: Sequence[ConcreteProtocol]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<neuroml xmlns="http://www.neuroml.org/schema/neuroml2" '
        'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
        'xsi:schemaLocation="http://www.neuroml.org/schema/neuroml2 '
        'https://raw.githubusercontent.com/NeuroML/NeuroML2/master/Schemas/NeuroML2/NeuroML_v2.3.1.xsd" '
        'id="ns_probe">',
        f"    <!-- Generated by NeuroSem. Protocols: {', '.join(p.protocol_id for p in protocols)} -->",
        f"    <include href={quoteattr(cell_include)}/>",
    ]
    inputs: list[tuple[str, str, str]] = []
    pulse_lines: list[str] = []
    ramp_lines: list[str] = []
    for p in protocols:
        pop = population_id(p.protocol_id)
        for i, comp in enumerate(p.components):
            cid = f"{pop}_c{i}"
            xml = _component_xml(cid, comp)
            (pulse_lines if comp.kind == "pulse" else ramp_lines).append(xml)
            inputs.append((cid, pop, p.protocol_id))
    lines += pulse_lines + ramp_lines   # NeuroML v2.3.1 InputTypes sequence: pulseGenerator* before rampGenerator*
    if model.temperature.strip():
        lines.append(f'    <network id="{PROBE_NET_ID}" type="networkWithTemperature" temperature={quoteattr(model.temperature)}>')
    else:
        lines.append(f'    <network id="{PROBE_NET_ID}">')
    for p in protocols:
        pop = population_id(p.protocol_id)
        lines += [
            f'        <population id="{pop}" component="{model.cell_id}" type="populationList" size="1">',
            '            <instance id="0"><location x="0" y="0" z="0"/></instance>',
            "        </population>",
        ]
    for cid, pop, _ in inputs:
        lines += [
            f'        <inputList id="{cid}_in" component="{cid}" population="{pop}">',
            f'            <input id="0" target="../{pop}/0/{model.cell_id}" destination="synapses"/>',
            "        </inputList>",
        ]
    lines += ["    </network>", "</neuroml>", ""]
    return "\n".join(lines)


def lems_xml(model: ModelRecord, net_include: str, protocols: Sequence[ConcreteProtocol], exec_cfg: ExecConfig,
             output_file: str, length_ms: float, seed: int = DEFAULT_SEED) -> str:
    lines = [
        "<Lems>",
        "    <!-- Generated by NeuroSem -->",
        f'    <Target component="{PROBE_SIM_ID}"/>',
        '    <Include file="Cells.xml"/>',
        '    <Include file="Networks.xml"/>',
        '    <Include file="Simulation.xml"/>',
        f"    <Include file={quoteattr(net_include)}/>",
        f'    <Simulation id="{PROBE_SIM_ID}" length="{format_number(length_ms)}ms" '
        f'step="{format_number(exec_cfg.dt_ms)}ms" target="{PROBE_NET_ID}" seed="{seed}">',
    ]
    if exec_cfg.integrator_method:
        lines.append(f'        <Meta for="jlems" method={quoteattr(exec_cfg.integrator_method)}/>')
    lines.append(f'        <OutputFile id="ns_v" fileName={quoteattr(output_file)}>')
    for p in protocols:
        pop = population_id(p.protocol_id)
        lines.append(f'            <OutputColumn id="{pop}_v" quantity="{pop}/0/{model.cell_id}/v"/>')
    lines += ["        </OutputFile>", "    </Simulation>", "</Lems>", ""]
    return "\n".join(lines)


def write_probe(ws: Workspace, protocols: Sequence[ConcreteProtocol], exec_cfg: ExecConfig, tag: str = "probe",
                seed: int = DEFAULT_SEED) -> ProbeBundle:
    """Write probe network + LEMS files into the workspace, next to the cell file."""
    if not protocols:
        raise ValueError("no protocols")
    ids = [p.protocol_id for p in protocols]
    if len(set(ids)) != len(ids):
        raise ValueError("duplicate protocol ids in one probe")
    cell_dir = ws.cell_path.parent
    safe_tag = re.sub(r"[^A-Za-z0-9_]", "_", tag)
    net_name = f"ns_{safe_tag}.net.nml"
    lems_name = f"LEMS_ns_{safe_tag}.xml"
    out_name = f"ns_{safe_tag}_v.dat"
    length = max(p.total_ms for p in protocols)
    (cell_dir / net_name).write_text(network_xml(ws.model, ws.cell_path.name, protocols), encoding="utf-8")
    (cell_dir / lems_name).write_text(lems_xml(ws.model, net_name, protocols, exec_cfg, out_name, length, seed),
                                      encoding="utf-8")
    columns = {pid: i + 1 for i, pid in enumerate(ids)}
    steps = int(round(length / exec_cfg.dt_ms))
    return ProbeBundle(cell_dir / lems_name, cell_dir / net_name, OutputSpec(out_name, columns), length,
                       tuple(ids), steps * len(protocols))


def group_by_length(protocols: Sequence[ConcreteProtocol]) -> list[list[ConcreteProtocol]]:
    """Batch protocols that share a total duration (avoids simulating short cells for the longest run)."""
    groups: dict[float, list[ConcreteProtocol]] = defaultdict(list)
    for p in protocols:
        groups[p.total_ms].append(p)
    return [groups[k] for k in sorted(groups)]


def canonical_output(model: ModelRecord) -> OutputSpec:
    return OutputSpec(model.harness_output_file, {"P00_canonical": int(model.harness_v_column)})


_STEP_RE = re.compile(r'(<(?:Simulation|Component)\b[^>]*?\bstep=")([^"]+)(")', re.DOTALL)
_LENGTH_RE = re.compile(r'(<(?:Simulation|Component)\b[^>]*?\blength=")([^"]+)(")', re.DOTALL)


def harness_step_and_length(text: str) -> tuple[str, str]:
    s, l = _STEP_RE.search(text), _LENGTH_RE.search(text)
    if not (s and l):
        raise ValueError("could not find Simulation step/length in harness")
    return s.group(2), l.group(2)
