"""Evaluation metrics, cluster-aware paired inference and paper figures (ARCHITECTURE.md section 3.8)."""

from neuraxis.analysis.bootstrap import (
    MIN_RELIABLE_CLUSTERS,
    SmallClusterWarning,
    cluster_bootstrap_diff,
    cluster_bootstrap_rate,
    cluster_permutation_details,
    cluster_permutation_test,
    exact_mcnemar,
    paired_comparison,
)
from neuraxis.analysis.metrics import (
    as_binary,
    as_count,
    as_label,
    as_labels,
    by_family,
    class_counts,
    coverage_curve,
    detection_rate,
    false_positive_rate,
    false_positive_summary,
    paired_counts,
    proportion_ci,
    protocols_to_reach,
    runtime_per_detection,
    silent_survival_rate,
    summarize_draws,
    validation_cascade,
)

__all__ = [
    "MIN_RELIABLE_CLUSTERS",
    "SmallClusterWarning",
    "as_binary",
    "as_count",
    "as_label",
    "as_labels",
    "by_family",
    "class_counts",
    "cluster_bootstrap_diff",
    "cluster_bootstrap_rate",
    "cluster_permutation_details",
    "cluster_permutation_test",
    "coverage_curve",
    "detection_rate",
    "exact_mcnemar",
    "false_positive_rate",
    "false_positive_summary",
    "paired_comparison",
    "paired_counts",
    "proportion_ci",
    "protocols_to_reach",
    "runtime_per_detection",
    "silent_survival_rate",
    "summarize_draws",
    "validation_cascade",
]
