"""Verification stage for model-curation candidates (runs after ``curate_candidates.py fetch``).

For every candidate (and every screened-out model kept for evidence) this script records:

1. ``jnml -validate`` on the cell file (the NeuroSem structural oracle) and on the harness network.
2. A structural read of the cell XML: number of segments, channel densities and any element that
   is not a NeuroML core type (custom LEMS types break NeuroSem's mutation operators).
3. The shipped LEMS harness, copied to ``work/tmp/model-curation/runs/<model_id>/`` and run at its
   own time step and length, with spike times compared to the shipped OMV ``.mep`` reference
   when there is one (OMV engines use their own tolerances; here we only report the deviation).
   Only the pinned snapshot (fetched include closure) is copied, so a successful run also shows the
   closure is complete.
4. Whether the cell responds to injected current at all (an inclusion criterion of the spec).
5. A bracketing rheobase search and a short rheobase-scaled current-clamp battery generated by
   ``neurosem.protocols``. The derived numbers are *screening metrics* computed with simple
   NumPy rules, not NeuroSem eFEL features and not calibrated results; they only check whether
   the expected behaviour class (bursting, sag, rebound, adaptation) is plausibly present.
6. For cells with an Ih conductance (``channelDensity ion="h"``): an Ih-block control, i.e. the same
   hyperpolarising protocols at the same absolute currents on a work copy with that density set to 0.
   The control-minus-block difference is what attributes depolarising recovery (sag) to Ih; without
   it a recovery could come from any slow current.

Every record carries a ``run_id`` and ``code_state_id`` (SHA-256 of the core modules this script
calls, this script and the simulator version). Records from a different code state are never merged
into one file silently.

Outputs: ``verification.json`` and one figure per model under ``figures/``.
Usage: python docs/m0_evidence/model_curation/verify_candidates.py [--models ID ...] [--no-probes] [--drop-stale]
"""

from __future__ import annotations

import argparse
import concurrent.futures as cf
import dataclasses as dc
import hashlib
import json
import re
import shutil
import subprocess
import sys
import time
import uuid
from pathlib import Path

import numpy as np
import yaml
from lxml import etree

from neurosem.models import Workspace
from neurosem.protocols.definitions import DEFAULT_TEMPLATES, ProtocolTemplate
from neurosem.protocols.generate import group_by_length, harness_step_and_length, write_probe
from neurosem.protocols.rheobase import make_step_counter, search
from neurosem.provenance import utc_now
from neurosem.schemas import AnalysisWindow, ConcreteProtocol, ExecConfig, ModelRecord, RunStatus, StimulusComponent
from neurosem.simulators.base import OutputSpec
from neurosem.simulators.jneuroml import JNeuroML

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
CANDIDATES_ROOT = REPO_ROOT / "models" / "candidates"
WORK = REPO_ROOT / "work" / "tmp" / "model-curation"
OUT_JSON = HERE / "verification.json"
FIG_DIR = HERE / "figures"

NML_NS = "{http://www.neuroml.org/schema/neuroml2}"
CORE_MEMBRANE = {"channelDensity", "channelDensityNernst", "channelDensityGHK", "channelDensityGHK2",
                 "channelDensityVShift", "channelDensityNonUniform", "channelDensityNonUniformNernst",
                 "channelDensityNonUniformGHK", "channelPopulation", "spikeThresh", "specificCapacitance",
                 "initMembPotential"}
SPIKE_THRESHOLD_MV = -20.0          # configs/study.yaml rheobase.spike_threshold_mV
PROBE_DT_MS = 0.01                  # screening resolution; tolerances are calibrated later, not here
SETTLE_MS = 300.0                   # configs/study.yaml numerics.settle_ms
FALLBACK_RHEOBASE_NA = 0.1          # configs/study.yaml rheobase.fallback_rheobase_nA

# Sag screen. The baseline is the mean V over the 50 ms before the step; a spike within that window (or
# 5 ms before it, whose AHP reaches into it) makes the baseline depend on spike phase, so sag is undefined.
SAG_PRE_WINDOW_MS = 50.0
SPIKE_GUARD_MS = 5.0
# "Late" minimum: taken from 30 ms after onset, so an AHP just after onset is not read as the trough.
SAG_LATE_OFFSET_MS = 30.0
EDGE_TOLERANCE_MS = 1.0

# A long, strong hyperpolarisation gives slow Ih (tens to hundreds of ms) time to activate, so sag
# is visible even when the default 500 ms, -1 x rheobase step is too weak to show it.
EXTRA_TEMPLATES = (
    ProtocolTemplate("S01_hyper_long", "step", "Long hyperpolarising step (-3 x rheobase, 1 s)",
                     {"multiple": -3.0, "duration_ms": 1000, "post_ms": 300}, ()),
)
PROBE_IDS = ("P01_baseline", "P04_step_2x", "P05_long_step", "P07_hyperpolarizing_step", "P08_rebound")
IH_BLOCK_PROTOCOLS = ("P01_baseline", "P07_hyperpolarizing_step", "P08_rebound", "S01_hyper_long")
IH_COMPARE_KEYS = ("mean_v_mV", "spike_count", "baseline_mV", "min_mV", "min_late_mV", "steady_mV",
                   "recovery_late_mV", "sag_ratio", "sag_ratio_late", "spikes_during_step", "rebound_spikes")

# Files whose content determines the numbers in verification.json.
CODE_FILES = ("src/neurosem/simulators/jneuroml.py", "src/neurosem/simulators/base.py",
              "src/neurosem/protocols/generate.py", "src/neurosem/protocols/rheobase.py",
              "src/neurosem/protocols/definitions.py", "src/neurosem/models.py", "src/neurosem/schemas.py",
              "docs/m0_evidence/model_curation/verify_candidates.py")


@dc.dataclass(frozen=True)
class Candidate:
    model_id: str
    snapshot: str
    cell_file: str
    cell_id: str
    harness_lems: str               # "" when no single-cell harness is shipped
    harness_output_file: str
    harness_v_column: int
    temperature: str
    net_file: str = ""              # NeuroML network included by the harness (validated too)
    mep: str = ""                   # shipped OMV reference, relative to the snapshot
    mep_experiment: str = ""
    mep_time_unit: str = "ms"       # unit of the .mep spike times
    mep_threshold_mV: float = 0.0   # detection threshold used by the matching .omt
    probe_cell_file: str = ""       # cell file for NeuroSem probes if it differs from cell_file
    probe_cell_id: str = ""
    role: str = "candidate"         # candidate | screen (kept only as evidence for an exclusion)


CANDIDATES: tuple[Candidate, ...] = (
    Candidate("prinz2004_abpd", "PyloricNetwork@e97696fc", "NeuroML2/AB_PD_3.cell.nml", "AB_PD",
              "NeuroML2/LEMS_Fig2a.xml", "AB_PD.dat", 1, "10.0 degC", net_file="NeuroML2/Fig2a.net.nml"),
    Candidate("prinz2004_lp", "PyloricNetwork@e97696fc", "NeuroML2/LP_2.cell.nml", "LP",
              "NeuroML2/LEMS_Fig2a.xml", "LP.dat", 1, "10.0 degC", net_file="NeuroML2/Fig2a.net.nml"),
    Candidate("maex1998_granule", "GranCellLayer@cee86047", "NeuroML2/Granule_98.cell.nml", "Granule_98",
              "", "", 1, "32.0 degC"),
    Candidate("maex1998_golgi", "GranCellLayer@cee86047", "NeuroML2/Golgi_98.cell.nml", "Golgi_98",
              "", "", 1, "32.0 degC"),
    Candidate("smith2013_singlecomp", "SmithEtAl2013-L23DendriticSpikes@179c596e",
              "NeuroML2/singleCompAllChans.cell.nml", "cell", "NeuroML2/LEMS_singleCompAllChans.xml",
              "jlems_sccct.dat", 1, "35 degC", net_file="NeuroML2/singleCompAllChans.net.nml",
              mep="NEURON/test/.test.mep", mep_experiment="spiking"),
    Candidate("migliore2014_mt_soma", "MiglioreEtAl14_OlfactoryBulb3D@eaad1c8f",
              "NeuroML2/Channels/test/MT_soma.cell.nml", "MT_soma", "NeuroML2/Channels/test/LEMS_OlfactoryTest_12.xml",
              "CG_MT_soma_0.0.dat", 1, "12.0 degC", net_file="NeuroML2/Channels/test/OlfactoryTest_12.net.nml",
              mep="NeuroML2/Channels/test/.test.12.mep", mep_experiment="mt"),
    Candidate("migliore2014_gc_soma", "MiglioreEtAl14_OlfactoryBulb3D@eaad1c8f",
              "NeuroML2/Channels/test/GC_soma.cell.nml", "GC_soma", "NeuroML2/Channels/test/LEMS_OlfactoryTest_12.xml",
              "CG_GC_soma_0.0.dat", 1, "12.0 degC", net_file="NeuroML2/Channels/test/OlfactoryTest_12.net.nml",
              mep="NeuroML2/Channels/test/.test.12.mep", mep_experiment="gc"),
    Candidate("solinas2007_soma_helper", "SolinasEtAl-GolgiCell@ab450696", "NeuroML2/TestSoma_HELPER.cell.nml",
              "TestSoma", "NeuroML2/LEMS_Soma_Test_HELPER.xml", "Soma.v.dat", 1, "23 degC",
              net_file="NeuroML2/TestSoma_HELPER.net.nml", mep="NEURON/test/.test.soma.mep",
              mep_experiment="pacemaking", mep_time_unit="s", role="screen"),
    # Screened out, kept as evidence (TestSoma_HELPER above is also a screen: its cell file fails
    # jnml -validate because <include> uses a 'file' attribute, so its channels only resolve through
    # the shipped LEMS file's explicit <Include>s):
    Candidate("solinas2007_testsoma", "SolinasEtAl-GolgiCell@ab450696", "NeuroML2/TestSoma.cell.nml", "TestSoma",
              "NeuroML2/LEMS_Soma_Test.xml", "Soma.v.dat", 1, "23 degC", net_file="NeuroML2/TestSoma.net.nml",
              role="screen"),
    Candidate("pinskyrinzel1994", "PinskyRinzelModel@a9aa9c90", "NeuroML2/twoCompartment/twoCompartmentCell.cell.nml",
              "pr2A", "NeuroML2/twoCompartment/LEMS_Figure2.xml", "Fig2A_Vs.dat", 1, "",
              mep="NeuroML2/twoCompartment/.test.fig2.mep", mep_experiment="Fig2A_Vs", mep_threshold_mV=-25.0,
              probe_cell_file="NeuroML2/twoCompartment/Figure2Aand3.parameters.nml", probe_cell_id="pr2A",
              role="screen"),
)


# ----------------------------------------------------------------------------- helpers
def interp_spike_times(t_ms: np.ndarray, v_mV: np.ndarray, thr: float) -> np.ndarray:
    """Upward threshold crossings, linearly interpolated between samples."""
    above = v_mV >= thr
    idx = np.flatnonzero(~above[:-1] & above[1:])
    v0, v1 = v_mV[idx], v_mV[idx + 1]
    return t_ms[idx] + (thr - v0) / (v1 - v0) * (t_ms[idx + 1] - t_ms[idx])


def _f(x) -> float | None:
    return None if x is None or not np.isfinite(x) else round(float(x), 4)


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def spiking_metrics(t: np.ndarray, v: np.ndarray, start: float, end: float) -> dict:
    st = interp_spike_times(t, v, SPIKE_THRESHOLD_MV)
    st = st[(st >= start) & (st < end)]
    isi = np.diff(st)
    out = {"spike_count": int(st.size), "first_spike_latency_ms": _f(st[0] - start) if st.size else None,
           "mean_rate_hz": _f(st.size / ((end - start) / 1e3)),
           "first_isi_ms": _f(isi[0]) if isi.size else None, "last_isi_ms": _f(isi[-1]) if isi.size else None,
           "isi_last_over_first": _f(isi[-1] / isi[0]) if isi.size >= 2 else None,
           "isi_cv": _f(isi.std() / isi.mean()) if isi.size >= 3 else None, "burst_gaps": None,
           "spikes_per_burst": None}
    if isi.size >= 3:
        # A "burst gap" is an ISI more than 3x the median ISI; >= 2 gaps with >= 2 spikes per burst on
        # average is labelled bursting. Crude, but enough to separate tonic from bursting trains.
        gaps = int(np.count_nonzero(isi > 3.0 * np.median(isi)))
        out["burst_gaps"] = gaps
        out["spikes_per_burst"] = _f(st.size / (gaps + 1))
    return out


def subthreshold_metrics(t: np.ndarray, v: np.ndarray, start: float, end: float, post_ms: float) -> dict:
    """Screening metrics for a hyperpolarising step.

    ``sag_ratio = (V_steady - V_min) / (V_baseline - V_min)``, with V_steady the mean over the last 10 %
    of the step. It is reported as undefined (None, with reasons) instead of as a misleading number when
    (1) a spike falls in or just before the pre-step baseline window, because the baseline mean then
    depends on spike phase, not on the resting potential (spontaneously active cells); or (2) the cell
    spikes during the step, because V_min can then be an AHP. ``sag_ratio_late`` takes V_min from 30 ms
    after onset and is also undefined when that minimum lies on the window edge (V still in the onset
    transient). ``recovery_late_mV = V_steady - V_min(late)`` needs no baseline, so it stays defined in
    spontaneously active cells; it is the quantity compared in the Ih-block control. None of these
    alone attributes a recovery to Ih.
    """
    st = interp_spike_times(t, v, SPIKE_THRESHOLD_MV)
    pre = (t >= start - SAG_PRE_WINDOW_MS) & (t < start)
    win = (t >= start) & (t < end)
    late = (t >= start + SAG_LATE_OFFSET_MS) & (t < end)
    tail = (t >= end - 0.1 * (end - start)) & (t < end)
    post = (t >= end) & (t < end + post_ms)
    base = float(v[pre].mean())
    i_min, i_late = int(np.argmin(v[win])), int(np.argmin(v[late]))
    vmin, vmin_late = float(v[win][i_min]), float(v[late][i_late])
    t_min, t_min_late = float(t[win][i_min] - start), float(t[late][i_late] - start)
    vss = float(v[tail].mean())
    n_pre = int(np.count_nonzero((st >= start - SAG_PRE_WINDOW_MS - SPIKE_GUARD_MS) & (st < start)))
    n_during = int(np.count_nonzero((st >= start) & (st < end)))

    common: list[str] = []
    if n_pre:
        common.append("spike in pre-step baseline window (baseline depends on spike phase)")
    if n_during:
        common.append("spike during step (minimum may be an AHP)")

    def ratio(v_trough: float, reasons: list[str]) -> float | None:
        if base - v_trough <= 1.0:
            reasons.append("deflection below baseline <= 1 mV")
        return None if reasons else _f((vss - v_trough) / (base - v_trough))

    reasons_all, reasons_late = list(common), list(common)
    if t_min_late - SAG_LATE_OFFSET_MS <= EDGE_TOLERANCE_MS:
        reasons_late.append("late-window minimum on the window edge (onset transient)")
    sag, sag_late = ratio(vmin, reasons_all), ratio(vmin_late, reasons_late)
    return {"baseline_mV": _f(base), "pre_window_min_mV": _f(v[pre].min()), "pre_window_max_mV": _f(v[pre].max()),
            "pre_window_spikes": n_pre, "min_mV": _f(vmin), "t_min_ms": _f(t_min), "min_late_mV": _f(vmin_late),
            "t_min_late_ms": _f(t_min_late), "steady_mV": _f(vss),
            "sag_ratio": sag, "sag_ratio_undefined_reasons": reasons_all,
            "sag_ratio_late": sag_late, "sag_ratio_late_undefined_reasons": reasons_late,
            "recovery_late_mV": None if n_during else _f(vss - vmin_late),
            "spikes_during_step": n_during,
            "rebound_spikes": int(np.count_nonzero((st >= end) & (st < end + post_ms))),
            "post_release_max_mV": _f(v[post].max()) if post.any() else None}


def find_cell(root: etree._Element, cell_id: str) -> etree._Element | None:
    # cell2CaPools (two independent Ca pools) is a NeuroML v2 core cell type, like cell.
    cells = [c for tag in ("cell", "cell2CaPools") for c in root.iter(f"{NML_NS}{tag}") if c.get("id") == cell_id]
    return cells[0] if cells else None


def structure(cell_path: Path, cell_id: str) -> dict:
    root = etree.parse(str(cell_path)).getroot()
    custom_types = [ct.get("name") for ct in root.iter(f"{NML_NS}ComponentType")]
    cell = find_cell(root, cell_id)
    info: dict = {"custom_component_types": custom_types, "standard_cell_element": cell is not None,
                  "cell_element": etree.QName(cell).localname if cell is not None else None}
    if cell is None:
        return info
    segs = cell.findall(f"{NML_NS}morphology/{NML_NS}segment")
    info["n_segments"] = len(segs)
    info["single_compartment"] = len(segs) == 1
    bio = cell.find(f"{NML_NS}biophysicalProperties")
    if bio is None:                       # biophysicalProperties2CaPools and similar custom containers
        bio = next((e for e in cell if isinstance(e.tag, str) and "biophysicalProperties" in e.tag), None)
    info["biophysical_container"] = etree.QName(bio).localname if bio is not None else None
    chans, noncore = [], []
    if bio is not None:
        for mp in bio:
            if not isinstance(mp.tag, str):
                continue
            for el in mp:
                if not isinstance(el.tag, str):
                    continue
                name = etree.QName(el).localname
                if "membraneProperties" in etree.QName(mp).localname:
                    if name not in CORE_MEMBRANE:
                        noncore.append(name)
                    if name.startswith("channel"):
                        chans.append({"element": name, "id": el.get("id"), "ionChannel": el.get("ionChannel"),
                                      "ion": el.get("ion"), "condDensity": el.get("condDensity"),
                                      "erev": el.get("erev")})
            if etree.QName(mp).localname not in ("membraneProperties", "intracellularProperties"):
                noncore.append(etree.QName(mp).localname)
    info["channels"] = chans
    info["non_core_elements"] = sorted(set(noncore))
    return info


def h_densities(cell: etree._Element) -> list[etree._Element]:
    """Channel densities of the cell that carry the h (Ih) current, identified by ``ion="h"``."""
    return [el for el in cell.iter() if isinstance(el.tag, str)
            and etree.QName(el).localname.startswith("channelDensity") and el.get("ion") == "h"]


def block_ih(cell_path: Path, cell_id: str) -> list[dict]:
    """Set every Ih density of ``cell_id`` in ``cell_path`` (a work copy) to 0, keeping its unit.

    Returns what was changed; an empty list means the cell has no Ih density and nothing was written.
    """
    tree = etree.parse(str(cell_path))
    cell = find_cell(tree.getroot(), cell_id)
    if cell is None:
        raise ValueError(f"{cell_path}: no cell {cell_id}")
    changed = []
    for el in h_densities(cell):
        orig = el.get("condDensity")
        if orig is None:
            raise ValueError(f"{cell_path}: Ih density {el.get('id')} has no condDensity; cannot block it")
        zero = re.sub(r"^\s*[-+0-9.eE]+\s*", "0 ", orig)
        el.set("condDensity", zero)
        changed.append({"element": etree.QName(el).localname, "id": el.get("id"), "ionChannel": el.get("ionChannel"),
                        "condDensity_original": orig, "condDensity_blocked": zero})
    if changed:
        tree.write(str(cell_path), xml_declaration=True, encoding="UTF-8")
    return changed


def copy_snapshot(snapshot: str, dest: Path) -> Path:
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(CANDIDATES_ROOT / snapshot, dest, ignore=shutil.ignore_patterns("PROVENANCE.json"))
    return dest


def model_record(c: Candidate, cell_file: str, cell_id: str) -> ModelRecord:
    blank = {f.name: "" for f in dc.fields(ModelRecord)}
    return ModelRecord(**{**blank, "model_id": c.model_id, "snapshot": c.snapshot, "cell_file": cell_file,
                          "cell_id": cell_id, "temperature": c.temperature, "harness_v_column": "1",
                          "inclusion": "candidate"})


def mep_compare(c: Candidate, t: np.ndarray, v: np.ndarray) -> dict | None:
    if not c.mep:
        return None
    doc = yaml.safe_load((CANDIDATES_ROOT / c.snapshot / c.mep).read_text(encoding="utf-8"))
    expected = np.asarray(doc["experiments"][c.mep_experiment]["expected"]["spike times"], dtype=float)
    if c.mep_time_unit == "s":
        expected = expected * 1e3
    observed = interp_spike_times(t, v, c.mep_threshold_mV)
    n = min(expected.size, observed.size)
    dev = np.abs(observed[:n] - expected[:n]) if n else np.array([])
    return {"mep": c.mep, "experiment": c.mep_experiment, "threshold_mV": c.mep_threshold_mV,
            "n_expected": int(expected.size), "n_observed": int(observed.size),
            "max_abs_dev_ms_paired": _f(dev.max()) if n else None,
            "median_abs_dev_ms_paired": _f(np.median(dev)) if n else None,
            "expected_first": [round(float(x), 3) for x in expected[:10]],
            "observed_first": [round(float(x), 3) for x in observed[:10]]}


def code_state(sim: JNeuroML) -> dict:
    """Hashes of everything that determines the numbers, so records from different states are never mixed.

    File hashes rather than a git commit, because the working tree can differ from HEAD (core modules
    were edited by other agents during the curation session).
    """
    files = {rel: _sha256_file(REPO_ROOT / rel) for rel in CODE_FILES}
    simulator = sim.version_info()
    head = subprocess.run(["git", "-C", str(REPO_ROOT), "rev-parse", "HEAD"], capture_output=True, text=True)
    state_id = hashlib.sha256(json.dumps({"files": files, "simulator": simulator}, sort_keys=True,
                                         default=str).encode()).hexdigest()[:16]
    return {"state_id": state_id, "files_sha256": files, "simulator": simulator,
            "git_head": head.stdout.strip() or None}


# ----------------------------------------------------------------------------- stages
def run_harness(sim: JNeuroML, c: Candidate) -> tuple[dict, tuple[np.ndarray, np.ndarray] | None]:
    if not c.harness_lems:
        return {"status": "not_shipped", "note": "no single-cell LEMS harness in the repository"}, None
    root = copy_snapshot(c.snapshot, WORK / "runs" / c.model_id)
    lems = root / c.harness_lems
    step, length = harness_step_and_length(lems.read_text(encoding="utf-8"))
    res = sim.run_lems(lems, [OutputSpec(c.harness_output_file, {"v": c.harness_v_column})], timeout_s=3600)
    rec = {"status": res.status.value, "returncode": res.returncode, "runtime_s": round(res.runtime_s, 2),
           "harness_step": step, "harness_length": length, "message": res.message}
    if res.status is not RunStatus.OK:
        return rec, None
    tr = res.traces["v"]
    st = interp_spike_times(tr.t_ms, tr.v_mV, SPIKE_THRESHOLD_MV)
    rec.update({"n_samples": int(tr.t_ms.size), "t_end_ms": _f(tr.t_ms[-1]), "v_min_mV": _f(tr.v_mV.min()),
                "v_max_mV": _f(tr.v_mV.max()), "spike_count_thr_minus20mV": int(st.size),
                "spike_times_ms_first20": [round(float(x), 3) for x in st[:20]],
                "mep_comparison": mep_compare(c, tr.t_ms, tr.v_mV)})
    return rec, (tr.t_ms, tr.v_mV)


def run_battery(sim: JNeuroML, ws: Workspace, protos: list[ConcreteProtocol], exec_cfg: ExecConfig, tag: str,
                cost: list) -> tuple[dict, dict]:
    """Run protocols (batched by length) and compute screening metrics per protocol."""
    metrics: dict = {}
    traces: dict = {}
    for gi, group in enumerate(group_by_length(protos)):
        b = write_probe(ws, group, exec_cfg, tag=f"{tag}_{gi}")
        r = sim.run_lems(b.lems_file, [b.output], timeout_s=3600)
        cost.append({"tag": f"{tag}_{gi}", "cell_steps": b.cell_steps, "runtime_s": round(r.runtime_s, 2),
                     "status": r.status.value})
        for p in group:
            if r.status is not RunStatus.OK:
                metrics[p.protocol_id] = {"status": r.status.value, "message": r.message}
                continue
            tr = r.traces[p.protocol_id]
            traces[p.protocol_id] = (tr.t_ms, tr.v_mV)
            comp = p.components[0]
            start, end = comp.delay_ms, comp.delay_ms + comp.duration_ms
            if p.kind == "baseline":
                metrics[p.protocol_id] = {"status": "ok", **spiking_metrics(tr.t_ms, tr.v_mV, start, end),
                                          "mean_v_mV": _f(tr.v_mV[(tr.t_ms >= start) & (tr.t_ms < end)].mean())}
            elif comp.amplitude_nA < 0:
                metrics[p.protocol_id] = {"status": "ok", "amplitude_nA": _f(comp.amplitude_nA),
                                          **subthreshold_metrics(tr.t_ms, tr.v_mV, start, end, 300.0)}
            else:
                metrics[p.protocol_id] = {"status": "ok", "amplitude_nA": _f(comp.amplitude_nA),
                                          **spiking_metrics(tr.t_ms, tr.v_mV, start, end)}
    return metrics, traces


def compare_ih_block(control: dict, blocked: dict) -> dict:
    out: dict = {}
    for pid, b in blocked.items():
        cm = control.get(pid, {})
        row = {}
        for k in IH_COMPARE_KEYS:
            if k in b or k in cm:
                x, y = cm.get(k), b.get(k)
                d = _f(y - x) if isinstance(x, (int, float)) and isinstance(y, (int, float)) else None
                row[k] = {"control": x, "ih_block": y, "block_minus_control": d}
        out[pid] = row
    return out


def run_ih_block(sim: JNeuroML, c: Candidate, cell_file: str, cell_id: str, protos: list[ConcreteProtocol],
                 exec_cfg: ExecConfig, control: dict, cost: list) -> tuple[dict | None, dict]:
    """Ih-block control: same protocols and absolute currents with every ``ion="h"`` density set to 0."""
    cell = find_cell(etree.parse(str(CANDIDATES_ROOT / c.snapshot / cell_file)).getroot(), cell_id)
    if cell is None or not h_densities(cell):
        return None, {}
    root = copy_snapshot(c.snapshot, WORK / "probes" / f"{c.model_id}__ih_block")
    changed = block_ih(root / cell_file, cell_id)
    v = sim.validate([root / cell_file])
    ws = Workspace(root, model_record(c, cell_file, cell_id))
    chosen = [p for p in protos if p.protocol_id in IH_BLOCK_PROTOCOLS]
    metrics, traces = run_battery(sim, ws, chosen, exec_cfg, "ihblock", cost)
    rec = {"method": "work copy of the snapshot with every channelDensity ion='h' of the cell set to 0; same "
                     "protocols, same absolute currents (control protocol scale), same dt",
           "blocked_densities": changed,
           "validate_blocked_cell": {"valid": v.valid, "returncode": v.returncode, "messages": v.messages[:5]},
           "battery": metrics, "comparison": compare_ih_block(control, metrics),
           "caveat": "Blocking Ih also shifts the resting potential and so recruits other voltage-dependent "
                     "currents differently; the difference is Ih's net effect in this model, not an isolated current."}
    return rec, traces


def run_probes(sim: JNeuroML, c: Candidate) -> tuple[dict, dict, dict]:
    cell_file = c.probe_cell_file or c.cell_file
    cell_id = c.probe_cell_id or c.cell_id
    root = copy_snapshot(c.snapshot, WORK / "probes" / c.model_id)
    ws = Workspace(root, model_record(c, cell_file, cell_id))
    exec_cfg = ExecConfig(dt_ms=PROBE_DT_MS)
    out: dict = {"dt_ms": PROBE_DT_MS, "spike_threshold_mV": SPIKE_THRESHOLD_MV, "cost": []}
    traces: dict = {}

    # (a) does injected current move the membrane potential at all? Tiny somata (a 10 um granule cell
    # has an input resistance of several GOhm) are pushed hundreds of mV outside the range where HH
    # rate exponentials stay finite by a 0.05 nA step, and jLEMS then aborts mid-run. So a failed run is
    # retried at 10x smaller amplitudes, and the rheobase search starts from 10x the amplitude that ran.
    attempts: list[dict] = []
    amp = 0.0
    for i, amp in enumerate((0.05, 0.005, 0.0005)):
        inj = [ConcreteProtocol(pid, "step", (StimulusComponent("pulse", SETTLE_MS, 500.0, a),), SETTLE_MS + 700.0,
                                AnalysisWindow(SETTLE_MS, SETTLE_MS + 500.0), ())
               for pid, a in (("I0_zero", 0.0), ("I1_plus", amp), ("I2_minus", -amp))]
        b = write_probe(ws, inj, exec_cfg, tag=f"inject_{i}")
        r = sim.run_lems(b.lems_file, [b.output], timeout_s=3600)
        out["cost"].append({"tag": f"inject_{i}", "cell_steps": b.cell_steps, "runtime_s": round(r.runtime_s, 2),
                            "status": r.status.value})
        attempts.append({"amplitude_nA": amp, "status": r.status.value, "message": r.message[:300]})
        if r.status is RunStatus.OK:
            break
    out["injection_attempts"] = attempts
    if r.status is not RunStatus.OK:
        out["injection_check"] = {"status": r.status.value, "message": r.message}
        return out, traces, {}
    t0 = r.traces["I0_zero"].t_ms
    m = (t0 >= SETTLE_MS) & (t0 < SETTLE_MS + 500.0)
    dplus = float(np.max(np.abs(r.traces["I1_plus"].v_mV[m] - r.traces["I0_zero"].v_mV[m])))
    dminus = float(np.max(np.abs(r.traces["I2_minus"].v_mV[m] - r.traces["I0_zero"].v_mV[m])))
    responds = max(dplus, dminus) > 0.5
    out["injection_check"] = {"status": "ok", "amplitudes_nA": [0.0, amp, -amp], "max_abs_dv_plus_mV": _f(dplus),
                              "max_abs_dv_minus_mV": _f(dminus), "responds_to_current": responds,
                              "zero_current_spikes_in_window": int(interp_spike_times(
                                  t0[m], r.traces["I0_zero"].v_mV[m], SPIKE_THRESHOLD_MV).size)}
    traces["I0_zero"] = (t0, r.traces["I0_zero"].v_mV)
    if not responds:
        return out, traces, {}

    # (b) rheobase
    cost: list = []
    counter = make_step_counter(sim, ws, exec_cfg, settle_ms=SETTLE_MS, step_ms=500.0,
                                threshold_mV=SPIKE_THRESHOLD_MV, tag="rheo", cost_log=cost)
    rh = search(counter, hi_nA=10.0 * amp, grid=8, rounds=3, expand=4.0, max_hi_nA=32.0)
    out["cost"] += cost
    out["rheobase"] = {"rheobase_nA": _f(rh.rheobase_nA), "status": rh.status, "resolution_nA": _f(rh.resolution_nA),
                       "n_simulations": rh.n_simulations}
    scale = rh.rheobase_nA if rh.status == "ok" and rh.rheobase_nA else FALLBACK_RHEOBASE_NA
    out["protocol_scale_nA"] = scale
    out["protocol_scale_source"] = "rheobase" if rh.status == "ok" else f"fallback ({rh.status})"

    # (c) rheobase-scaled screening battery
    templates = {t.protocol_id: t for t in (*DEFAULT_TEMPLATES, *EXTRA_TEMPLATES)}
    protos = [templates[p].instantiate(scale, SETTLE_MS) for p in (*PROBE_IDS, "S01_hyper_long")]
    out["battery"], battery_traces = run_battery(sim, ws, protos, exec_cfg, "battery", out["cost"])
    traces.update(battery_traces)

    # (d) Ih-block control (only for cells with an h-current density)
    out["ih_block"], block_traces = run_ih_block(sim, c, cell_file, cell_id, protos, exec_cfg, out["battery"],
                                                 out["cost"])
    return out, traces, block_traces


def figure(c: Candidate, harness: tuple | None, traces: dict, block_traces: dict) -> str | None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    panels = ([("harness", harness)] if harness else []) + [(k, v) for k, v in traces.items()]
    if not panels:
        return None
    fig, axes = plt.subplots(len(panels), 1, figsize=(7, 1.4 * len(panels)), sharex=False, squeeze=False)
    for ax, (name, (t, v)) in zip(axes[:, 0], panels):
        ax.plot(t, v, lw=0.6, color="black", label="control")
        if name in block_traces:
            tb, vb = block_traces[name]
            ax.plot(tb, vb, lw=0.6, color="tab:red", alpha=0.8, label="Ih blocked")
            ax.legend(fontsize=5, loc="lower right", frameon=False)
        ax.set_ylabel("mV", fontsize=7)
        ax.set_title(name, fontsize=7, loc="left")
        ax.tick_params(labelsize=6)
        ax.ticklabel_format(axis="y", useOffset=False)
    axes[-1, 0].set_xlabel("time (ms)", fontsize=7)
    fig.suptitle(f"{c.model_id} (screening runs, not calibrated results)", fontsize=8)
    fig.tight_layout()
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    path = FIG_DIR / f"{c.model_id}.png"
    fig.savefig(path, dpi=80)
    plt.close(fig)
    return path.relative_to(REPO_ROOT).as_posix()


def verify_one(sim: JNeuroML, c: Candidate, probes: bool, run_id: str, state_id: str) -> dict:
    t_start = time.perf_counter()
    snap = CANDIDATES_ROOT / c.snapshot
    rec: dict = {"model_id": c.model_id, "role": c.role, "run_id": run_id, "code_state_id": state_id,
                 "candidate": dc.asdict(c), "started_utc": utc_now()}
    v = sim.validate([snap / c.cell_file])
    rec["validate_cell"] = {"valid": v.valid, "returncode": v.returncode, "messages": v.messages[:10]}
    if c.net_file:
        vn = sim.validate([snap / c.net_file])
        rec["validate_network"] = {"file": c.net_file, "valid": vn.valid, "returncode": vn.returncode,
                                   "messages": vn.messages[:10]}
    rec["structure"] = structure(snap / c.cell_file, c.cell_id)
    rec["harness"], harness_trace = run_harness(sim, c)
    traces: dict = {}
    block_traces: dict = {}
    if probes:
        try:
            rec["probes"], traces, block_traces = run_probes(sim, c)
        except Exception as exc:  # recorded, never hidden: a probe failure is itself evidence
            rec["probes"] = {"error": f"{type(exc).__name__}: {exc}"}
    rec["figure"] = figure(c, harness_trace, traces, block_traces)
    rec["wall_time_s"] = round(time.perf_counter() - t_start, 1)
    return rec


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--models", nargs="*")
    ap.add_argument("--no-probes", action="store_true")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--drop-stale", action="store_true",
                    help="discard earlier records made under a different code state instead of refusing to run")
    args = ap.parse_args(argv)
    sim = JNeuroML()
    if not sim.available():
        raise SystemExit("Java/jNeuroML unavailable")
    chosen = [c for c in CANDIDATES if not args.models or c.model_id in args.models]
    chosen_ids = {c.model_id for c in chosen}
    state = code_state(sim)
    started = utc_now()
    run_id = f"{started}_{uuid.uuid4().hex[:8]}"

    previous = json.loads(OUT_JSON.read_text(encoding="utf-8")) if OUT_JSON.exists() else {"models": {}}
    kept = {m: r for m, r in previous.get("models", {}).items() if m not in chosen_ids}
    stale = sorted(m for m, r in kept.items() if r.get("code_state_id") != state["state_id"])
    if stale and not args.drop_stale:
        raise SystemExit(f"{OUT_JSON.name} holds records from a different code state for {stale}; re-run them in "
                         "this invocation (omit --models) or pass --drop-stale")
    results = {m: r for m, r in kept.items() if m not in stale}
    runs = {rid: meta for rid, meta in previous.get("runs", {}).items()
            if any(r.get("run_id") == rid for r in results.values())}

    with cf.ThreadPoolExecutor(max_workers=args.workers) as pool:
        futs = {pool.submit(verify_one, sim, c, not args.no_probes, run_id, state["state_id"]): c for c in chosen}
        for fut in cf.as_completed(futs):
            c = futs[fut]
            try:
                results[c.model_id] = fut.result()
            except Exception as exc:
                results[c.model_id] = {"model_id": c.model_id, "run_id": run_id, "code_state_id": state["state_id"],
                                       "error": f"{type(exc).__name__}: {exc}"}
            r = results[c.model_id]
            print(f"{c.model_id}: validate={r.get('validate_cell', {}).get('valid')} "
                  f"harness={r.get('harness', {}).get('status')} "
                  f"spikes={r.get('harness', {}).get('spike_count_thr_minus20mV')} wall={r.get('wall_time_s')}s", flush=True)
    end_state = code_state(sim)
    if end_state["state_id"] != state["state_id"]:
        print("WARNING: code state changed during the run; records are flagged", flush=True)
    runs[run_id] = {"started_utc": started, "finished_utc": utc_now(), "models": sorted(chosen_ids),
                    "probes": not args.no_probes, "code_state": state,
                    "code_state_changed_during_run": end_state["state_id"] != state["state_id"]}
    doc = {"generated_utc": utc_now(), "method": __doc__.strip().splitlines()[0],
           "caveat": "Screening metrics from single deterministic runs; not eFEL features, not calibrated, "
                     "and finite testing is not evidence of equivalence.",
           "provenance_rule": "each model record names its run_id and code_state_id; records from a different "
                              "code state are never merged into this file",
           "runs": runs, "models": dict(sorted(results.items()))}
    OUT_JSON.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
